version: 2.1
parameters:
  trusted_publish:
    type: boolean
    default: false
  packages:
    type: string
    default: ''

aliases:
  - &defaults
    docker:
      - image: cimg/node:22.18.0
  - &restore_cache
    restore_cache:
      key: yarn-cache-{{ checksum "yarn.lock" }}
  - &install_yarn
    run:
      name: 'Installing correct yarn version'
      command: |
        corepack enable --install-directory="/home/circleci/bin"
        yarn set version 4.18.0
  - &install_dependencies
    run:
      name: 'Installing dependencies'
      command: 'yarn install'
  - &save_cache
    save_cache:
      key: yarn-cache-{{ checksum "yarn.lock" }}
      paths:
        - ~/.cache/yarn

jobs:
  ci:
    <<: *defaults
    steps:
      - checkout
      - *restore_cache
      - *install_yarn
      - *install_dependencies
      - *save_cache
      - run: 'yarn run ci'
  trusted-publish:
    <<: *defaults
    steps:
      - checkout
      - *restore_cache
      - *install_yarn
      - *install_dependencies
      - *save_cache
      - run: yarn run ci --trusted-publish "<< pipeline.parameters.packages >>"

workflows:
  version: 2
  # On every commit
  commit:
    when: not pipeline.parameters.trusted_publish
    jobs:
      - ci
  trusted-publish:
    when: pipeline.parameters.trusted_publish
    jobs:
      - trusted-publish
